services:
  bun:
    image: imbios/bun-node:latest
    user: $UID:$UID
    command: bun run dev
    ports:
      - ${DOCS_MAPPED_PORT:-5173}:5173
    volumes:
      - ./:/home/bun/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  node:
    image: node:lts
    user: $UID:$UID
    command: node index.ts
    ports:
      - ${DOCS_MAPPED_PORT:-5173}:5173
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
